baseURL = "https://ibishovrauf.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
theme = "blowfish"

enableRobotsTXT = true
enableEmoji = true

mainSections = ["projects"]

[pagination]
  pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML", "RSS"]
